schema_version = "1.0.0"

id = "yl_vertexcolforge"
version = "1.1.0"
name = "YL VertexColForge"
tagline = "Vertex color channel tools for packed masks"
maintainer = "YLIANG"
type = "add-on"
website = "https://github.com/YLIANG021/YL-VertexColForge"

license = ["SPDX:GPL-3.0-or-later"]
blender_version_min = "4.2.0"
tags = ["Mesh", "Paint"]
